version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_KEY=${OPENAI_KEY}
      - ORG_ID=${ORG_ID}
      - OPENAI_4O=${OPENAI_4O}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
